name = "ai-coding-assistant-workers"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# Production environment
[env.production]
name = "ai-coding-assistant-workers-prod"
vars = { ENVIRONMENT = "production" }

# Staging environment
[env.staging]
name = "ai-coding-assistant-workers-staging"
vars = { ENVIRONMENT = "staging" }

# KV Namespaces (uncomment when needed)
# [[kv_namespaces]]
# binding = "AI_ASSISTANT_KV"
# preview_id = "preview_kv_namespace_id"
# id = "production_kv_namespace_id"

# R2 Buckets (uncomment when needed)
# [[r2_buckets]]
# binding = "AI_ASSISTANT_R2"
# bucket_name = "ai-assistant-storage"
# preview_bucket_name = "ai-assistant-storage-preview"

# Vectorize (uncomment when needed)
# [[vectorize]]
# binding = "AI_ASSISTANT_VECTORIZE"
# index_name = "ai-assistant-embeddings" 